"""
Инициализация категорий по умолчанию
"""
from models import Category, CategoryType

DEFAULT_CATEGORIES = [
    # Доходы
    Category(name="Зарплата", type=CategoryType.INCOME, color="#4CAF50", icon="💰"),
    Category(name="Фриланс", type=CategoryType.INCOME, color="#2196F3", icon="💼"),
    Category(name="Инвестиции", type=CategoryType.INCOME, color="#9C27B0", icon="📈"),
    Category(name="Дивиденды", type=CategoryType.INCOME, color="#FF9800", icon="📊"),
    Category(name="Подарки", type=CategoryType.INCOME, color="#00BCD4", icon="🎁"),
    Category(name="Возврат", type=CategoryType.INCOME, color="#FFC107", icon="↪️"),
    Category(name="Прочие доходы", type=CategoryType.INCOME, color="#9E9E9E", icon="💵"),

    # Расходы
    Category(name="Продукты", type=CategoryType.EXPENSE, color="#8BC34A", icon="🛒"),
    Category(name="Супермаркет", type=CategoryType.EXPENSE, color="#4CAF50", icon="🏪"),
    Category(name="Кафе и рестораны", type=CategoryType.EXPENSE, color="#FF5722", icon="🍽️"),
    Category(name="Транспорт", type=CategoryType.EXPENSE, color="#3F51B5", icon="🚗"),
    Category(name="Такси", type=CategoryType.EXPENSE, color="#2196F3", icon="🚕"),
    Category(name="Общественный транспорт", type=CategoryType.EXPENSE, color="#03A9F4", icon="🚌"),
    Category(name="Бензин", type=CategoryType.EXPENSE, color="#FF9800", icon="⛽"),
    Category(name="Жилье", type=CategoryType.EXPENSE, color="#795548", icon="🏠"),
    Category(name="Аренда", type=CategoryType.EXPENSE, color="#8D6E63", icon="🏡"),
    Category(name="Ипотека", type=CategoryType.EXPENSE, color="#A1887F", icon="🏚️"),
    Category(name="Коммуналка", type=CategoryType.EXPENSE, color="#607D8B", icon="💡"),
    Category(name="Электричество", type=CategoryType.EXPENSE, color="#FFC107", icon="⚡"),
    Category(name="Вода", type=CategoryType.EXPENSE, color="#00BCD4", icon="💧"),
    Category(name="Газ", type=CategoryType.EXPENSE, color="#FF5722", icon="🔥"),
    Category(name="Интернет", type=CategoryType.EXPENSE, color="#3F51B5", icon="🌐"),
    Category(name="Телевидение", type=CategoryType.EXPENSE, color="#9C27B0", icon="📺"),
    Category(name="Развлечения", type=CategoryType.EXPENSE, color="#E91E63", icon="🎮"),
    Category(name="Кино", type=CategoryType.EXPENSE, color="#F44336", icon="🎬"),
    Category(name="Концерты", type=CategoryType.EXPENSE, color="#9C27B0", icon="🎤"),
    Category(name="Хобби", type=CategoryType.EXPENSE, color="#FF9800", icon="🎨"),
    Category(name="Спорт", type=CategoryType.EXPENSE, color="#4CAF50", icon="⚽"),
    Category(name="Здоровье", type=CategoryType.EXPENSE, color="#009688", icon="🏥"),
    Category(name="Лекарства", type=CategoryType.EXPENSE, color="#FF5722", icon="💊"),
    Category(name="Стоматолог", type=CategoryType.EXPENSE, color="#00BCD4", icon="🦷"),
    Category(name="Страховка", type=CategoryType.EXPENSE, color="#3F51B5", icon="🛡️"),
    Category(name="Образование", type=CategoryType.EXPENSE, color="#FFC107", icon="📚"),
    Category(name="Курсы", type=CategoryType.EXPENSE, color="#FF9800", icon="🎓"),
    Category(name="Книги", type=CategoryType.EXPENSE, color="#795548", icon="📖"),
    Category(name="Одежда", type=CategoryType.EXPENSE, color="#FF4081", icon="👕"),
    Category(name="Обувь", type=CategoryType.EXPENSE, color="#E91E63", icon="👠"),
    Category(name="Аксессуары", type=CategoryType.EXPENSE, color="#9C27B0", icon="💍"),
    Category(name="Техника", type=CategoryType.EXPENSE, color="#673AB7", icon="💻"),
    Category(name="Смартфон", type=CategoryType.EXPENSE, color="#3F51B5", icon="📱"),
    Category(name="Ноутбук", type=CategoryType.EXPENSE, color="#2196F3", icon="💻"),
    Category(name="Планшет", type=CategoryType.EXPENSE, color="#00BCD4", icon="📟"),
    Category(name="Путешествия", type=CategoryType.EXPENSE, color="#03A9F4", icon="✈️"),
    Category(name="Отели", type=CategoryType.EXPENSE, color="#FF9800", icon="🏨"),
    Category(name="Авиабилеты", type=CategoryType.EXPENSE, color="#2196F3", icon="🎫"),
    Category(name="Налоги", type=CategoryType.EXPENSE, color="#F44336", icon="📋"),
    Category(name="Подоходный налог", type=CategoryType.EXPENSE, color="#D32F2F", icon="💼"),
    Category(name="Налог на имущество", type=CategoryType.EXPENSE, color="#C2185B", icon="🏠"),
    Category(name="Прочие расходы", type=CategoryType.EXPENSE, color="#757575", icon="📦"),
]
