# -*- coding: utf-8 -*-
"""Лаба1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ZPQ_AnDI_Yzr7EnNwKg0J18ZGDfOr9n
"""

a = 5
b = input('b: ')

while not b.isdigit():
    b = input()

print(a * int(b))

a = input('a: ')
b = input('b: ')

while not a.isdigit() or not b.isdigit():
    print('надо ввести числа!')
    a = input('a: ')
    b = input('b: ')

print(f'Результат: {(int(a) + int(b))**2}')

a = 15
b = 10
c = input('c: ')

while not c.isdigit() and c == '0':
  print('Надо ввести число и не 0')
  с = input('c: ')

print((a + b) / int(c))

a = input("a: ")
b = input("b: ")

while not a.isdigit() or not b.isdigit():
    print('Надо ввести числа!')
    a = input("a: ")
    b = input("b: ")

c = int(a)**2 + 2*int(a)*int(b) + int(b)**2
print(f"{a}**2 + 2 * {a} * {b} + {b}**2 = {c}")

from math import sqrt

a = input("a: ")
b = input("b: ")
c = input("c: ")

check_a = not a.isdigit() or a == '0' or '-' in a
check_b = not b.isdigit() or b == '0' or '-' in b
check_c = not c.isdigit() or c == '0' or '-' in c

while check_a or check_b or check_c:
    print("Нужно положительное число")
    a = input("a: ")
    b = input("b: ")
    c = input("c: ")

    check_a = not a.isdigit() or a == '0' or '-' in a
    check_b = not b.isdigit() or b == '0' or '-' in b
    check_c = not c.isdigit() or c == '0' or '-' in c

a = int(a)
b = int(b)
c = int(c)

P = a + b + c
p = P/2
S = sqrt(p*(p-a)*(p-b)*(p-c))

print(f"P = {P}")
print(f"S = {S}")

a = input("a: ")
b = input("b: ")

while not a.isdigit() or not b.isdigit():
    print("Надо ввести числа!")
    a = input("a: ")
    b = input("b: ")

c = ((int(a)**3 + 14)/5) * int(b)
print(c)

a = input("a: ")

while not a.isdigit():
    print("a - целое число")
    a = input("a: ")

n = input("n: ")

while not n.isdigit() or n == '0':
    print("n - целое число и оно не может быть равное 0")
    n = input("n: ")

c = int(a)**2 // int(n)
print(f"{a}**2 // {n} = {c}")

def is_float(x):
    try:
        float(x)
        return True
    except ValueError:
        print("Введите дробное число!")
        return False

def input_two_int():
    a, b = two_input()

    while not a.isdigit() or not b.isdigit():
        print("Введите натуральные числа! ")
        a, b = two_input()

    return a, b

def two_input():
    a = input("a: ")
    b = input("b: ")

    return a, b

a, b = two_input()

while not is_float(a) or not is_float(b):
    a, b = two_input()

c = float(a)//float(b)
print(f"Результат для первого задания: {c}")

a, b = input_two_int()

print(f"Результат для второго задания: {int(a) * int(b)} ")
print(f"Результат для третьего задания: {int(a) % int(b)} ")

n = input()

while not n.isdigit():
    print("Введите целое число")
    n = input()

n = int(n)
minutes = n // 60 % 60
hours = n // 3600 % 24
days = n // (3600 * 24)

print(f"{days}/{hours}/{minutes}")

n = input()

while not n.isdigit():
    print("Введите целое число")
    n = input()

print(int(n) + int(n*2) + int(n*3))